HW1 done
Halyna443/prjc_HP_JS pull request #1
Opened 2023-10-03 13:44 UTC by Halyna443

Homework 1.

2023-10-04 16:19 UTC, myroslav-kolomiiets requested changes
Добра робота.

Лише невеликі правки.

2023-10-04 16:19 UTC, myroslav-kolomiiets commented on hw_01.js
> +for (const userName of userNames) {
Рішення робоче, що добре. Але два вкладених цикла не дуже оптимально. Можна розглянути альтернативний варіант з використанням методу map

2023-10-04 16:19 UTC, myroslav-kolomiiets commented on hw_01.js
> +        stringInitials = stringInitials + part.charAt(0) + ".";
```suggestion
        stringInitials = stringInitials + part[0] + ".";
```
Можна спростити

2023-10-04 16:19 UTC, myroslav-kolomiiets commented on hw_01.js
> +//   if (['У', 'Е', 'І', 'А', 'О', 'Є', 'Я', 'Ю', 'И'].includes(firstLetter)) {
Масив з літерами краще винести в окрему змінну.

2023-10-04 16:19 UTC, myroslav-kolomiiets commented on hw_01.js
> +// for (let i = 0; i < userNames.length; i++) {
Загалом це ок. Але використання методу forEach буде зручніше і не доведеться звертатись до елемента масива по індексу

2023-10-04 16:19 UTC, myroslav-kolomiiets commented on hw_01.js
> +// const filteredNames = userNames.filter(userNames => /^[уеіаоєяюУЕІАОЄЯЮ]/.test(userNames));
Всюди де можна обійтись без регулярок - краще обходитись без регулярок

2023-10-04 16:19 UTC, myroslav-kolomiiets commented on hw_01.js
> +// let reverseMaxValue = stringMaxValue.split('').reverse().join('');
Тут можна обійтись без створення змінної. 

В решті все вірно, окремий плюс за використання явних перетворень.

2023-10-04 16:19 UTC, myroslav-kolomiiets commented on hw_01.js
> +// const initArray = 1;
Назва не коректна, оскільки це не масив

2023-10-04 16:19 UTC, myroslav-kolomiiets commented on hw_01.js
> +//         // console.log(previous, current);
Консолі ітд краще прибирати перед відправкою коду на перевірку

2023-10-04 16:19 UTC, myroslav-kolomiiets commented on hw_01.js
> +// let productOfArray = flatArray.reduce(
Ця змінна також не потрібна, reduce можна викликати зразу за flat

2023-10-09 11:59 UTC, Halyna443 commented on hw_01.js
> +for (const userName of userNames) {
Використала метод 'map' замість двох циклів.

2023-10-09 12:00 UTC, Halyna443 commented on hw_01.js
> +        stringInitials = stringInitials + part.charAt(0) + ".";
Використала звертання по індексу.

2023-10-09 12:02 UTC, Halyna443 commented on hw_01.js
> +//   if (['У', 'Е', 'І', 'А', 'О', 'Є', 'Я', 'Ю', 'И'].includes(firstLetter)) {
Для масиву з літерами створила окрему змінну.

2023-10-09 12:03 UTC, Halyna443 commented on hw_01.js
> +// for (let i = 0; i < userNames.length; i++) {
Переробила, використала метод 'forEach'.

2023-10-09 12:05 UTC, Halyna443 commented on hw_01.js
> +// const filteredNames = userNames.filter(userNames => /^[уеіаоєяюУЕІАОЄЯЮ]/.test(userNames));
Зробила без використання регулярного виразу.

2023-10-09 12:05 UTC, Halyna443 commented on hw_01.js
> +// let reverseMaxValue = stringMaxValue.split('').reverse().join('');
Переробила без створення змінної.

2023-10-09 12:06 UTC, Halyna443 commented on hw_01.js
> +// const initArray = 1;
Змінила назву.

2023-10-09 12:06 UTC, Halyna443 commented on hw_01.js
> +// const initArray = 1;
Змінила назву.

2023-10-09 12:06 UTC, Halyna443 commented on hw_01.js
> +//         // console.log(previous, current);
Прибрала 'консолі'.

2023-10-09 12:10 UTC, Halyna443 commented on hw_01.js
> +// let productOfArray = flatArray.reduce(
Прибрала зайву змінну.

2023-10-09 18:17 UTC, myroslav-kolomiiets requested changes

2023-10-09 18:17 UTC, myroslav-kolomiiets commented on hw_01.js
> +//     const vowelLetter = ['У', 'Е', 'І', 'А', 'О', 'Є', 'Я', 'Ю', 'И'];
```suggestion
// const filteredNames = [];
//     const vowelLetter = ['У', 'Е', 'І', 'А', 'О', 'Є', 'Я', 'Ю', 'И'];
// userNames.forEach(userName => {
//     const firstLetter = userName[0];
```
Зараз у вас на кожній ітерації, під капотом, створюється новий масив. Що звісно не оптимально

Його треба винести назовні з методу, тоді не буде лишнього використання пам'яті

2023-10-09 18:40 UTC, Halyna443 commented on hw_01.js
> +//     const vowelLetter = ['У', 'Е', 'І', 'А', 'О', 'Є', 'Я', 'Ю', 'И'];
Винесла масив з методу.

2023-10-09 18:40 UTC, Halyna443 commented on hw_01.js
> +//     const vowelLetter = ['У', 'Е', 'І', 'А', 'О', 'Є', 'Я', 'Ю', 'И'];
Винесла масив з методу.

2023-10-09 20:29 UTC, myroslav-kolomiiets approved these changes

2023-10-10 06:31 UTC, merged