Homework 02
Halyna443/prjc_HP_JS pull request #2
Opened 2023-10-10 15:52 UTC by Halyna443

Homework 2

2023-10-12 13:31 UTC, myroslav-kolomiiets requested changes

2023-10-12 13:31 UTC, myroslav-kolomiiets commented on hw_02.js
> +function getTimePeriod(startDate = new Date(), endDate = new Date(), unit = 'days') {
В цілому все норм, але є один нюанс. Дефолтні значення мають тип object, а в функцію передаються, при виклику, аргументи з типом string. Подумай як зробити, щоб і дефолтні аргументи та ті які передаються при виклику, мали однаковий тип.

2023-10-12 13:31 UTC, myroslav-kolomiiets commented on hw_02.js
> +        return timeDifference / 1000;
```suggestion
        return timeDifference / 1000;
```
Якщо у всіх умовах / 1000, то є сенс винести в одне місце, наприклад туди де обчислюється timeDifference

2023-10-12 13:31 UTC, myroslav-kolomiiets commented on hw_02.js
> +//         updatedData[lowerCaseKey] = price;
```suggestion
//         updatedData[lowerCaseKey] = Number(data[key]).toFixed(2);
```
Лишня змінна

2023-10-12 13:31 UTC, myroslav-kolomiiets commented on hw_02.js
> +//     }
```suggestion
//     }
//      return number + recursiveOddSumTo(number - 2);
```

2023-10-16 14:08 UTC, Halyna443 commented on hw_02.js
> +function getTimePeriod(startDate = new Date(), endDate = new Date(), unit = 'days') {
.toISOString() перетворює тип 'object' в тип 'string'. Використавши цей метод перетворила 'object' в 'string'.

2023-10-16 14:19 UTC, Halyna443 commented on hw_02.js
> +        return timeDifference / 1000;
Винесла, зробила ` const timeDifference = (laterDate - earlierDate) / 1000;`

2023-10-16 14:22 UTC, Halyna443 commented on hw_02.js
> +//         updatedData[lowerCaseKey] = price;
Прибрала зайву змінну.

2023-10-16 14:30 UTC, Halyna443 commented on hw_02.js
> +//     }
Скоротила запис.

2023-10-16 14:30 UTC, merged