homework_03 done
Halyna443/prjc_HP_JS pull request #3
Opened 2023-10-16 14:48 UTC by Halyna443

2023-10-18 09:25 UTC, myroslav-kolomiiets requested changes

2023-10-18 09:25 UTC, myroslav-kolomiiets commented on hw_03.js
> +//     for (let arg of args) sum += arg;
```suggestion
//     for (let arg of args) {
    sum += arg;
}
```
Дуже рекомендую звикати до такого форматування, і виділяти блоки коду явно, на проєктах 99.99% що у вас будуть саме такі налаштування лінтерів

2023-10-18 09:25 UTC, myroslav-kolomiiets commented on hw_03.js
> +//     return args.reduce((previous, current) => previous + current, 0);
вірно

2023-10-18 09:25 UTC, myroslav-kolomiiets commented on hw_03.js
> +// function multiply(a) {
вірно

2023-10-18 09:25 UTC, myroslav-kolomiiets commented on hw_03.js
> +return Array.from(new Set(array));
вірно

2023-10-18 09:25 UTC, myroslav-kolomiiets commented on hw_03.js
> +// function byProperty(property, direction) {
переускладнене рішення

фактично все що нам треба для успішного вирішення даної задачі це:

якщо символ === '>', то повертаємо функцію що перевіряє a[property] > b[property], якщо так то повертає 1, якщо ні то повертає -1

і якщо символ === '<', то повертаємо функцію що перевіряє a[property] < b[property] і якщо так, повертає 1, якщо ні, то повертає -1

якщо записувати умовні конструкції через тернарні оператори, то вийде взагалі в кілька рядків)

2023-10-22 11:22 UTC, Halyna443 commented on hw_03.js
> +//     for (let arg of args) sum += arg;
Виправила.

2023-10-22 12:56 UTC, Halyna443 commented on hw_03.js
> +// function byProperty(property, direction) {
Переробила згідно з твоїми рекомендаціями.

2023-10-23 11:22 UTC, myroslav-kolomiiets approved these changes

2023-10-24 14:03 UTC, merged